### ISSUE TITLE
Stop moving my cursor/caret to the next line on table mode

### ISSUE THREAD

**Issue by evandrocoan** [randy3k/AlignTab#78]
![back3](https://user-images.githubusercontent.com/5332158/37358727-941819f0-26ca-11e8-92ab-7c4dcaf5dc0d.gif)

I just pressed space after the last `|` pipe and a second later, the packaged moved my caret to the next line. My caret should stay where it is, on the trailing space after the last `|` pipe.

```
I = a  | b  | aP | bP
S = a  | 
```

**Comment by randy3k** [comment]
I could reproduce it.

**Comment by evandrocoan** [comment]
Thanks for the fix, it is much better now. But still something stranger happening:

![back3](https://user-images.githubusercontent.com/5332158/37571668-8978461a-2ade-11e8-83a1-b6399644d805.gif)

Right after I press space, the package it deletes it. I have to almost immediately type a letter, otherwise the space is erased;

**Comment by randy3k** [comment]
Well, it is not a bug per se. It is because AlignTab removes any trailing spaces. In table mode, the align command is fired after one second of the edit. If you want to add something to the table, 1) there is no need to type the first space, 2) if you really want to type the space, just make sure that it is followed by some non-space chars.

**Comment by evandrocoan** [comment]
Can I disable that? I my Sublime Text already trim the trailing whitespaces when I save the file. There is not need to dynamically trim whitespaces.

I type some real hard stuff, and I keep thinking some time before typing what I need. But I already put the empty whitespace beforehand, so, when I have to type, I do not need to remember to put the whitespace.
